### ISSUE TITLE
fix installation experience

### ISSUE THREAD

**Issue by josephhaaga** [josephhaaga/clerk#20]
1. need to warn users about updating PATH

```bash
$ pipx install josephhaaga-clerk  
  installed package josephhaaga-clerk 0.0.5, installed using Python 3.10.8
  These apps are now globally available
    - journal
⚠️  Note: '/Users/joehaaga/.local/bin' is not on your PATH environment variable. These apps will not be globally
    accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your
    PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
```

2. `user_config_dir` doesn't work out of the box! so we can't rely on this for setting up clerk, unless we rewrite the code to skip config validation when `import`ing `clerk.config`

```bash
$ pipx run josephhaaga-clerk python3 -c "import clerk.config; print(clerk.config.dirs().user_config_dir)"

NOTE: running app 'journal' from 'josephhaaga-clerk'
Your configuration at /Users/joehaaga/Library/Application Support/clerk/0.0.5/clerk.conf is missing a key 'journal_directory'
```

3. README [instructions for setting up configuration](https://github.com/josephhaaga/clerk/blob/713202fb52e33400471332506a945be6184b780c/README.md?plain=1#L43) don't work with `pipx` installation!
  * users need to run `pipx run josephhaaga-clerk python3 -c "import clerk.config; print(clerk.config.dirs().user_config_dir)"` to ensure the correct Python interpreter is being used

4. Users must manually create Journal directories at installation-time, or else they get a write error when they save/close a journal.

```bash
$ journal        
timestamp ran; changes applied!
Traceback (most recent call last):
  File "/Users/joehaaga/.local/bin/journal", line 8, in <module>
    sys.exit(main())
  File "/Users/joehaaga/.local/pipx/venvs/josephhaaga-clerk/lib/python3.10/site-packages/clerk/app.py", line 39, in main
    app.open_journal(date_as_filename)
  File "/Users/joehaaga/.local/pipx/venvs/josephhaaga-clerk/lib/python3.10/site-packages/clerk/app.py", line 124, in open_journal
    shutil.copy(journal.name, file_to_open)
  File "/Users/joehaaga/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/joehaaga/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/Journal/journals/2022-11-09.md'
```

**Comment by josephhaaga** [comment]
1 is just a README update

2 & 3 are no longer valid as of 7e8236a1f9ee78c7ae357f8abf3f0751511e9c81

4 is tricky - maybe we add some logic to `clerk/app.py` to raise an Exception if the designated directory doesn't exist?
