### ISSUE TITLE
allow tilde in journal_directory config option

### ISSUE THREAD

**Issue by josephhaaga** [josephhaaga/clerk#21]
potentially use `pathlib`'s `expanduser()` function
https://stackoverflow.com/a/41415165

## reproduction
```bash
$ cat /Users/joehaaga/Library/Application\ Support/clerk/0.0.5/clerk.conf      

[DEFAULT]
journal_directory=~/Documents/journal/journals/
preferred_editor=vi
date_format=%%Y-%%m-%%d
file_extension=md

[hooks]
JOURNAL_OPENED=
    timestamp

[timestamp]
format=%%Y-%%m-%%d %%I:%%M:%%S %%p
prefix=
    [
suffix=] 

$ journal                           
timestamp ran; changes applied!
Traceback (most recent call last):
  File "/Users/joehaaga/.local/bin/journal", line 8, in <module>
    sys.exit(main())
  File "/Users/joehaaga/.local/pipx/venvs/josephhaaga-clerk/lib/python3.10/site-packages/clerk/app.py", line 39, in main
    app.open_journal(date_as_filename)
  File "/Users/joehaaga/.local/pipx/venvs/josephhaaga-clerk/lib/python3.10/site-packages/clerk/app.py", line 124, in open_journal
    shutil.copy(journal.name, file_to_open)
  File "/Users/joehaaga/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/joehaaga/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/journal/journals/2022-11-09.md'
```

**Comment by josephhaaga** [comment]
need a test case for:
- `journal_directory=~/relative/path`
- `journal_directory=/Absolute/Path`
